version: '3'

services:

  mysqldb:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ArgdecDB1520
      MYSQL_DATABASE: arganddepxadmin
    ports:
      - "3306:3306"
    volumes:
      - "./newdata:/var/lib/mysql:rw"